name: Automation

on:
  repository_dispatch:
    types: [on-demand-docker-build]

env:
  PYTHON_VERSION: ${{ github.event.client_payload.PYTHON_VERSION }}
  POETRY_VERSION: ${{ github.event.client_payload.POETRY_VERSION }}
  MKDOCS_VERSION: ${{ github.event.client_payload.MKDOCS_VERSION }}
  MKDOCS_BUILD_PLANTUML_VERSION: ${{ github.event.client_payload.MKDOCS_BUILD_PLANTUML_VERSION }}
  PLANTUML_VERSION: ${{ github.event.client_payload.PLANTUML_VERSION }}

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Python version ${PYTHON_VERSION}"
      - run: echo "Poetry version ${POETRY_VERSION}"
      - run: echo "mkdocs version ${MKDOCS_VERSION}"
      - run: echo "mkdocs plantuml version ${MKDOCS_BUILD_PLANTUML_VERSION}"
      - run: echo "Plantuml version ${PLANTUML_VERSION}"
